LIB_DIR=-L../../systemc-2.3.3/lib-linux64
INC_DIR=-I../../systemc-2.3.3/include
LIB=-lsystemc

APP=arb_width_logic_type

all:
	g++ -o $(APP) $(APP).cpp $(LIB_DIR) $(INC_DIR) $(LIB)

clean:
	rm -rf $(APP)
